### ISSUE TITLE
Pathology orders: create order, items header and scroll issue it is not working proper.

### ISSUE THREAD

**Issue by urmadhan** [crawlinknetworks/clinicplus#38]
There is a gap above the header if u scroll items, it is visible above the header..

**Comment by crawlinknetworks** [comment]
Sticky table header border has the issue, So unset sticky table header th border.
```css
.sticky-table th {
  padding: 0.5rem;
  border: none;
}
```
